pub struct AssetPaths {
    pub fira_sans: &'static str,
    pub audio_digging: &'static str,
    pub audio_flying: &'static str,
    pub audio_fuel: &'static str,
    pub audio_waste: &'static str,
    pub texture_digger: &'static str,
    pub texture_background: &'static str,
    pub texture_border: &'static str,
    pub texture_tank_upgrade: &'static str,
    pub texture_stone: &'static str,
    pub texture_stone_mining: &'static str,
    pub texture_silver: &'static str,
    pub texture_silver_mining: &'static str,
    pub texture_gold: &'static str,
    pub texture_gold_mining: &'static str,
    pub texture_diamond: &'static str,
    pub texture_diamond_mining: &'static str,
    pub texture_base: &'static str,
    pub texture_waste: &'static str,
}

pub const PATHS: AssetPaths = AssetPaths {
    fira_sans: "fonts/FiraSans-Bold.ttf",
    audio_digging: "audio/drill.mp3",
    audio_flying: "audio/flying.mp3",
    audio_fuel: "audio/fuel.mp3",
    audio_waste: "audio/waste.mp3",
    texture_base: "textures/base.png",
    texture_digger: "textures/digger.png",
    texture_background: "textures/background.png",
    texture_tank_upgrade: "textures/tank_upgrade.png",
    texture_border: "textures/border.png",
    texture_stone: "textures/stone.png",
    texture_stone_mining: "textures/stone_mining.png",
    texture_silver: "textures/silver.png",
    texture_silver_mining: "textures/silver_mining.png",
    texture_gold: "textures/gold.png",
    texture_gold_mining: "textures/gold_mining.png",
    texture_diamond: "textures/diamond.png",
    texture_diamond_mining: "textures/diamond_mining.png",
    texture_waste: "textures/waste.png",
};
